name: Admin Web Build
run-name: Admin Web Build - ${{github.event.head_commit.message}}

on:
  workflow_dispatch:
  push:
    paths: 
      - admin-web/**
      - .github/workflows/admin-web-build.yml
    branches:
      - main

jobs:
  build:
    runs-on: ["self-hosted", "build"]
    name: Build Docker Image and Publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Registry
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}

      - name: Build Docker Image
        run:  docker build --build-arg VITE_API_URL=${{vars.API_URL}} --build-arg VITE_API_AUTH_ADMINTOKEN=${{secrets.AUTH_ADMINTOKEN}} -t bakery-admin-web:latest --platform linux/arm64 ./admin-web
        
      - name: Tag Image
        run: docker tag bakery-admin-web:latest  ${{ secrets.REGISTRY_URL }}/bakery-admin-web:latest

      - name: Push Image
        run: docker push ${{ secrets.REGISTRY_URL }}/bakery-admin-web:latest