name: Api Build
run-name: Api Build - ${{github.event.head_commit.message}}

on:
  workflow_dispatch:
  push:
    paths: 
      - api/**
      - .github/workflows/api-deploy.yml
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/api-test.yml
  build:
    needs: test
    runs-on: ["self-hosted", "build"]
    name: Build Docker Image and Publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Add User Secrets to App Config
        uses: microsoft/variable-substitution@v1
        with:
          files: './api/appconfig.json'
        env:
          Auth.Token: ${{secrets.AUTH_TOKEN}}
          Auth.AdminToken: ${{secrets.AUTH_ADMINTOKEN}}
          Database.Path: ${{ secrets.DATABASE_PATH }}
          Email.From: ${{ secrets.EMAIL_FROM }}
          Email.To: ${{ secrets.EMAIL_TO }}
          Email.Smtp.Host: ${{ secrets.EMAIL_SMTP_HOST }}
          Email.Smtp.Port: ${{ secrets.EMAIL_SMTP_PORT }}
          Email.Smtp.User: ${{ secrets.EMAIL_SMTP_USER }}
          Email.Smtp.Pass: ${{ secrets.EMAIL_SMTP_PASS }}

      - name: Login to Registry
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}

      - name: Build Image
        run: docker build -t bakery-api:latest --platform linux/arm64 ./api
        
      - name: Tag Image
        run: docker tag bakery-api:latest  ${{ secrets.REGISTRY_URL }}/bakery-api:latest

      - name: Push Image
        run: docker push ${{ secrets.REGISTRY_URL }}/bakery-api:latest