name: Api Build
run-name: Api Build - ${{github.event.head_commit.message}}

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        name: Build Docker Image and Publish
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Add User Secrets to App Config
              uses: microsoft/variable-substitution@v1
              with:
                files: './api/appconfig.json'
              env:
                Auth.Token: ${{secrets.AUTH_TOKEN}}
                Auth.AdminToken: ${{secrets.AUTH_ADMINTOKEN}}
                Database.Path: ${{ secrets.DATABASE_PATH }}
                Email.From: ${{ secrets.EMAIL_FROM }}
                Email.To: ${{ secrets.EMAIL_TO }}
                Email.Smtp.Host: ${{ secrets.EMAIL_SMTP_HOST }}
                Email.Smtp.Port: ${{ secrets.EMAIL_SMTP_PORT }}
                Email.Smtp.User: ${{ secrets.EMAIL_SMTP_USER }}
                Email.Smtp.Pass: ${{ secrets.EMAIL_SMTP_PASS }}

            - name: Login to Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                context: ./api
                push: true
                cache-from: type=gha
                tags: bakery-api:latest