name: Web Deploy
run-name: Web Deploy - ${{github.event.head_commit.message}}

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ["self-hosted", "deploy"]
    name: Deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Registry
        run: docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}

      - name: Remove Previous Version
        run: docker rm -f bakery-web || true

      - name: Create and Start Container
        run: docker run --name bakery-web --restart=always -p 5173:80 -d ${{ secrets.REGISTRY_URL }}/bakery-web:latest