name: Web Deploy

on:
    workflow_dispatch:
    push:
      paths: 
        - web/**
      branches:
        - main
    pull_request:
      paths: 
        - web/**
      types: [opened, synchronize, reopened, closed]
      branches:
        - main

jobs:
    deploy:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: self-hosted
        name: Build Docker Image and Deploy
        steps:
            - uses: actions/checkout@v3

            - name: Build Docker Image
              run:  docker build --build-arg VITE_API_URL=${{vars.API_URL}} --build-arg VITE_API_AUTH_TOKEN=${{secrets.AUTH_TOKEN}} -t bakery-web ./web

            - name: Remove Previous Version
              run: docker rm -f bakery-web || true

            - name: Create and Start Container
              run: docker run --name bakery-web -p 5173:80 -d bakery-web:latest